# Generated by Django 5.2.8 on 2026-04-16 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('cpu_capacity', models.BigIntegerField()),
                ('cache_capacity', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100, unique=True)),
                ('path', models.JSONField(default=list)),
                ('x_coord', models.FloatField(default=0)),
                ('y_coord', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('cpu_capacity', models.BigIntegerField()),
                ('cache_capacity', models.BigIntegerField()),
                ('is_mission', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rsu', 'RSU'), ('vehicle', 'Vehicle')], max_length=20)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
                ('rsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.rsu')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RSUVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('connect_time', models.FloatField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
                ('rsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.rsu')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.vehicle')),
            ],
        ),
    ]
