# Generated by Django 5.2.8 on 2026-04-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dag', '0001_initial'),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
                ('sp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.serviceprovider')),
                ('task_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dag.tasktype')),
            ],
        ),
    ]
