# Generated by Django 5.2.8 on 2025-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('path', models.JSONField(default=list)),
                ('height', models.FloatField()),
                ('speed', models.FloatField()),
                ('cpu_capacity', models.IntegerField()),
                ('cache_capacity', models.IntegerField()),
                ('is_mission', models.BooleanField(default=True)),
            ],
        ),
    ]
