# Generated by Django 5.2.8 on 2025-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100, unique=True)),
                ('path', models.JSONField(default=list)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('speed', models.FloatField()),
                ('length', models.FloatField(default=0)),
                ('cpu_capacity', models.BigIntegerField()),
                ('cache_capacity', models.BigIntegerField()),
                ('is_mission', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
