# Generated by Django 5.2.8 on 2025-12-20 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_used', models.BigIntegerField()),
                ('cache_used', models.BigIntegerField()),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('cpu_capacity', models.BigIntegerField()),
                ('cache_capacity', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSUVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('connect_time', models.FloatField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rsu', 'RSU'), ('vehicle', 'Vehicle')], max_length=20)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
