# Generated by Django 5.2.8 on 2025-12-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rsu', '0001_initial'),
        ('task', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='task_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tasktype'),
        ),
        migrations.AddField(
            model_name='rsuvehicle',
            name='rsu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsu.rsu'),
        ),
        migrations.AddField(
            model_name='rsuvehicle',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rsu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsu.rsu'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
        migrations.AddField(
            model_name='resource',
            name='sp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsu.serviceprovider'),
        ),
        migrations.AddField(
            model_name='cache',
            name='sp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsu.serviceprovider'),
        ),
    ]
