# Generated by Django 5.2.8 on 2025-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="index",
            field=models.TextField(),
        ),
    ]
