# Generated by Django 5.2.8 on 2025-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="index",
            field=models.TextField(max_length=200),
        ),
    ]
