# Generated by Django 5.2.8 on 2026-04-16 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('dag', '0001_initial'),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exec_time', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(default=0)),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
                ('application_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object.serviceprovider')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dag.task')),
            ],
        ),
    ]
