# Generated by Django 5.2.8 on 2026-04-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.BigIntegerField()),
                ('gain', models.FloatField()),
                ('distance', models.FloatField()),
                ('rate', models.FloatField()),
                ('initial_snapshot', models.JSONField(blank=True, null=True)),
                ('from_vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='From', to='object.vehicle')),
                ('task_execution_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.taskexecution')),
                ('to_rsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.rsu')),
                ('to_vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to', to='object.vehicle')),
            ],
        ),
    ]
